print('Operators comparison examples\n')
print('Is 1 equal (==) to 1?', 1 == 1)
print('Is 1 equal (==) to "1"?', 1 == '1')
print('Is 1 different (!=) from 2?', 1 != 2)
print('Is 3 greater (>) than 2?', 3 > 2)
print('Is 2 less (<) than 3?', 2 < 3)
print('Is 2 greater than (>=)  or equal to 2?', 2 >= 2)
print('Is 3 less than (<=) or equal to 2?', 3 <= 2)
print('Is 1 identical (is) to "1"?', 1 is '1')
print('Is 1 not identical (is not) to "1"?', 1 is not '1')
print('-'*60)